apiVersion: apps/v1
{{- if .Values.dataVolume.persist }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ include "realopinsight.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "realopinsight.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
{{- if .Values.dataVolume.persist }}
  serviceName: {{ include "realopinsight.fullname" . }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "realopinsight.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "realopinsight.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: 54583
        fsGroup: 54583
      {{- end }}
      serviceAccountName: {{ include "realopinsight.fullname" . }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.envs }}
          env:
          {{- range $key, $val := .Values.envs }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          ports:
            - name: http-ui
              containerPort: {{ .Values.service.targetPortUI }}
              protocol: TCP
            - name: http-metrics
              containerPort: {{ .Values.service.targetPortMetrics }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ui
              port: http-ui
          readinessProbe:
            httpGet:
              path: /ui
              port: http-ui
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.dataVolume.persist }}
          volumeMounts:
            - mountPath: /data
              name: data-vol
            - mountPath: /opt/realopinsight/etc
              name: config-data-vol
      volumes:
      - name: config-data-vol
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.dataVolume.capacity }}
{{- else }}
      - name: data-vol
        emptyDir: {}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
