apiVersion: v1
kind: Service
metadata:
  name: {{ include "realopinsight.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "realopinsight.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-ui
      protocol: TCP
      port: {{ .Values.service.portUI }}
      targetPort: {{ .Values.service.targetPortUI }}
    - name: http-metrics
      protocol: TCP
      port: {{ .Values.service.portMetrics }}
      targetPort: {{ .Values.service.targetPortMetrics }}
  selector:
    app.kubernetes.io/name: {{ include "realopinsight.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
