apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "realopinsight.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "realopinsight.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "realopinsight.fullname" . }}
  labels:
    {{- include "realopinsight.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  - services
  verbs:
  - get
  - list
  - watch
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "realopinsight.fullname" . }}
  labels:
    {{- include "realopinsight.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "realopinsight.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "realopinsight.fullname" . }}
  namespace: {{ .Release.Namespace }}
