---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: realopinsight
  namespace: monitoring
  labels:
    app.kubernetes.io/name: realopinsight
    app.kubernetes.io/instance: realopinsight
    app: realopinsight
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: realopinsight
  labels:
    app.kubernetes.io/name: realopinsight
    app.kubernetes.io/instance: realopinsight
    app: realopinsight
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  - services
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: realopinsight
  labels:
    app.kubernetes.io/name: realopinsight
    app.kubernetes.io/instance: realopinsight
    app: realopinsight
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: realopinsight
subjects:
- kind: ServiceAccount
  name: realopinsight
  namespace: monitoring
