---
apiVersion: v1
kind: Pod
metadata:
  name: "realopinsight-test-connection"
  labels:
    app.kubernetes.io/name: realopinsight
    app.kubernetes.io/instance: realopinsight
spec:
  containers:
    - name: wget
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - echo 'waiting 60s';
          sleep 60;
          wget 'realopinsight:80';
          echo done;
  restartPolicy: Never
