name: Build image on PR
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read

    concurrency:
      group: image-pr-${{ github.event.pull_request.number }}

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and push Docker image
      env:
        IMAGE_BASENAME: rchakode/realopinsight
        REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      run: |
        echo "setting build version"
        RELEASE_VERSION="$(date +%F)-$(git rev-parse --short HEAD)"
        VERSION_FILE=realopinsight.pro
        VERSION_LINE=$(grep -n '^PACKAGE_VERSION=' $VERSION_FILE | cut -f1 -d:)
        VERSION_ORIG=$(grep '^PACKAGE_VERSION=' $VERSION_FILE | cut -d= -f2)
        sed -i "${VERSION_LINE}s/${VERSION_ORIG}/${RELEASE_VERSION}/" $VERSION_FILE
        cat $VERSION_FILE

        echo "building container image => ${IMAGE_BASENAME}:${RELEASE_VERSION}"
        IMAGE_TAGGED_NAME=${IMAGE_BASENAME}:${RELEASE_VERSION}
        docker build -t ${IMAGE_TAGGED_NAME} .
        docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
        docker push $IMAGE_TAGGED_NAME
