name: Build image
on:
  push:
    tags:
      - v*

jobs:
  build:
    concurrency:
      group: image-${{ github.ref }}

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and push Docker image
      env:
        IMAGE_NAME: rchakode/realopinsight
        REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      run: |
        echo "computing build version"
        export GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        export IMAGE_TAG=$(echo $GIT_TAG | sed 's/v//')
        export RELEASE_VERSION=$IMAGE_TAG

        echo "patching final version in project file"
        VERSION_FILE=realopinsight.pro
        VERSION_LINE=$(grep -n '^PACKAGE_VERSION=' $VERSION_FILE | cut -f1 -d:)
        VERSION_ORIG=$(grep '^PACKAGE_VERSION=' $VERSION_FILE | cut -d= -f2)
        sed -i "${VERSION_LINE}s/${VERSION_ORIG}/${RELEASE_VERSION}/" $VERSION_FILE
        cat $VERSION_FILE

        echo "Building Docker image with tag => ${IMAGE_NAME}:${RELEASE_VERSION}"
        docker build -t ${IMAGE_NAME}:${RELEASE_VERSION} .
        
        docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
        
        echo "Pushing built image as latest"
        docker tag $IMAGE_NAME:${RELEASE_VERSION} ${IMAGE_NAME}:latest
        docker push $IMAGE_NAME:${RELEASE_VERSION}
        docker push $IMAGE_NAME
