name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    concurrency:
      group: ci-${{ github.ref }}

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        echo "building code"
        docker build --target builder .

